feat(mobile): ios添加书签到桌面逻辑更新
lkw199711/smanga pull request #21
Opened 2023-03-10 15:22 UTC by KevinJieZheng

对ios添加书签到桌面做全屏适配

2023-03-10 16:25 UTC, KevinJieZheng commented
更新列表页面和部分布局设置

2023-03-11 04:27 UTC, lkw199711 requested changes
1. 改变了之前的点击跳转逻辑变为emit 请阐述这里变更的需求
2. 页码的变更我认为不能够兼容安卓机型
3. 关于样式的改成 是否能够保持对安卓的兼容性

2023-03-11 04:27 UTC, lkw199711 commented on src/components/chapter.vue
> +      <!--封面图片-->
这里为何要使用emit的形式呢? 我看到并没有传递参数

2023-03-11 04:27 UTC, lkw199711 commented on src/components/chapter.vue
> +      this.$emit('more')
这里同理 我不太明白为何右侧菜单需要这种格式

2023-03-11 04:27 UTC, lkw199711 commented on src/components/media-pager.vue
> +          return 4;
页码这里我是测试过选取的 element的页码设置需要5-21的奇数 不然会报warnning, 我知道7对于苹果机器太多 但是我这个程序也不是专门为了苹果机器设计的, 在master做这样的改动并不好

2023-03-11 04:27 UTC, lkw199711 commented on src/components/media-pager.vue
> +  padding: 1.4rem 0px;
样式方面同理 不知道是否对Android机型也做了测试

2023-03-11 04:34 UTC, KevinJieZheng commented
1. 许多机型和移动端对长按有默认事件，保留原来长按逻辑，新增右下角图标对海报页面打开逻辑，emit解决的你原跳转方法的方式保留
2，页码变更只是长度调整和集中，兼容溢出对页面影响
3，手上没有安卓手机，添加到桌面不知道安卓适配情况

2023-03-11 04:37 UTC, KevinJieZheng commented on src/components/chapter.vue
> +      <!--封面图片-->
事件发生就行了，使用方法还是你自己的方法

2023-10-13 15:02 UTC, closed without merging